apiVersion: v1
kind: Secret
metadata:
  name: worker-secret
type: Opaque
stringData:
  DB_PASSWORD: CHANGE_ME_DB_PASSWORD
  MONGODB_URI: CHANGE_ME_MONGODB_URI
  MINIO_ACCESS_KEY: CHANGE_ME_MINIO_ACCESS_KEY
  MINIO_SECRET_KEY: CHANGE_ME_MINIO_SECRET_KEY
