apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
type: Opaque
stringData:
  DB_PASSWORD: CHANGE_ME_DB_PASSWORD
  SMTP_HOST: CHANGE_ME_SMTP_HOST
  SMTP_USER: CHANGE_ME_SMTP_USER
  SMTP_PASS: CHANGE_ME_SMTP_PASS
  INTERNAL_SERVICE_TOKEN: CHANGE_ME_INTERNAL_SERVICE_TOKEN
