apiVersion: v1
kind: Secret
metadata:
  name: media-secret
type: Opaque
stringData:
  DB_PASSWORD: CHANGE_ME_DB_PASSWORD
  MINIO_ACCESS_KEY: CHANGE_ME_MINIO_ACCESS_KEY
  MINIO_SECRET_KEY: CHANGE_ME_MINIO_SECRET_KEY
